import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const original='scene-105bfbad-4a6f-4174-98ea-c10341cda210',id='scene-e2e',dir=`data/scenes/${id}`;
fs.mkdirSync(dir,{recursive:true});
const source=JSON.parse(fs.readFileSync(`data/scenes/${original}/scene.json`,'utf8'));
fs.writeFileSync(`${dir}/scene.json`,JSON.stringify({...source,id,title:'검증용 현장',createdAt:'2000-01-01'}));
fs.copyFileSync(`data/scenes/${original}/hazards.json`,`${dir}/hazards.json`);
fs.rmSync(`${dir}/manual.json`,{force:true});
const errors=[],results={};let browser;
try {
 browser=await chromium.launch({headless:false,args:['--use-angle=metal']});
 const p=await browser.newPage({viewport:{width:1440,height:960}});p.on('pageerror',e=>errors.push(e.message));
 await p.goto(`http://127.0.0.1:3000/?scene=${id}`);
 await p.waitForFunction(()=>window.zipbulScene?.getInfo().ready,null,{timeout:90000});
 const before=await p.evaluate(()=>window.zipbulScene.getCamera());
 await p.locator('.hazard-card').first().click();
 assert.equal(await p.getByRole('button',{name:'대상 보기',exact:true}).isDisabled(),true);
 assert.deepEqual(await p.evaluate(()=>window.zipbulScene.getCamera()),before);results.proposedDoesNotFocus=true;
 await p.getByRole('button',{name:'촬영 시점',exact:true}).click();
 await p.waitForTimeout(900);await p.screenshot({path:'output/e2e-original.png'});
 await p.getByRole('button',{name:'보완 보기',exact:true}).click();await p.waitForTimeout(2500);
 await p.screenshot({path:'output/e2e-enhanced.png'});
 results.enhancedFps=await p.evaluate(()=>window.zipbulScene.getInfo().fps);
 await p.getByRole('button',{name:'수동 위치 연결',exact:true}).click();
 const marker=p.locator('.scene-marker').first();await marker.waitFor();const r=await marker.boundingBox();assert.ok(r);
 await p.mouse.click(r.x+r.width/2,r.y+r.height/2);
 await p.getByRole('button',{name:'이 위치로 연결',exact:true}).click();
 await p.waitForFunction(()=>document.querySelector('.location-state')?.textContent.includes('사용자 위치 연결'));
 assert.equal(await p.getByRole('button',{name:'대상 보기',exact:true}).isEnabled(),true);
 await p.locator('.review-section').getByRole('button',{name:'확인',exact:true}).click();
 await p.waitForTimeout(400);
 let snap=await (await fetch(`http://127.0.0.1:3001/api/scenes/${id}`)).json();
 assert.equal(snap.hazards[0].anchor.status,'verified');assert.equal(snap.hazards[0].review,'confirmed');results.manualMappingAndReview=true;
 await p.getByRole('button',{name:'전체 관계도',exact:true}).click();await p.waitForTimeout(1000);
 const fullCount=await p.locator('.react-flow__node').count();assert.ok(fullCount>=16);await p.screenshot({path:'output/e2e-graph-full.png'});
 await p.getByRole('button',{name:'집중 보기',exact:true}).click();await p.waitForTimeout(400);const focusCount=await p.locator('.react-flow__node').count();assert.ok(focusCount<fullCount);results.graph={fullCount,focusCount};
 await p.getByRole('button',{name:'탐사로 돌아가기',exact:true}).click();
 await p.reload();await p.waitForFunction(()=>window.zipbulScene?.getInfo().ready,null,{timeout:90000});
 await p.locator('.hazard-card').first().click();await p.waitForTimeout(300);assert.equal(await p.getByRole('button',{name:'대상 보기',exact:true}).isEnabled(),true);results.reloadPreservesMapping=true;
 await p.locator('#walk-mode').click();await p.getByRole('button',{name:'탐사 계속',exact:true}).click();await p.waitForTimeout(800);
 await p.evaluate(()=>window.advanceTime(100));
 const start=await p.evaluate(()=>window.zipbulScene.getInfo());
 await p.keyboard.down('KeyW');await p.evaluate(()=>window.advanceTime(500));await p.keyboard.up('KeyW');
 const moved=await p.evaluate(()=>window.zipbulScene.getInfo());const distance=Math.hypot(...moved.player.map((v,i)=>v-start.player[i]));
 assert.ok(distance>.05,`Movement only ${distance}`);assert.ok(distance<2);assert.ok(moved.grounded);results.movement={distance,start:start.player,end:moved.player,grounded:moved.grounded};
 await p.keyboard.press('Escape');await p.waitForTimeout(300);assert.equal((await p.evaluate(()=>window.zipbulScene.getInfo())).paused,true);results.escapePauses=true;
 await p.screenshot({path:'output/e2e-walk.png'});
 const stale=await fetch(`http://127.0.0.1:3001/api/scenes/${id}/hazards/${snap.hazards[0].id}/review`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'confirmed',manualRevision:0})});assert.equal(stale.status,409);results.staleWriteRejected=true;
 const range=await fetch(`http://127.0.0.1:3001${source.videoUrl}`,{headers:{Range:'bytes=0-99'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,100);results.videoRange=true;
 assert.deepEqual(errors,[]);results.errors=errors;
 fs.writeFileSync('output/e2e-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser?.close();fs.rmSync(dir,{recursive:true,force:true});}
