import fs from 'node:fs';import sharp from 'sharp';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
const id='scene-33a46c91-0ba7-44f8-99dc-bfe3588c539a',s=JSON.parse(fs.readFileSync(`data/scenes/${id}/scene.json`));
const tiles=[];for(const [i,f]of s.frames.entries()){const thumb=await sharp(s.files[f.id]).resize(320,240).toBuffer();tiles.push({input:thumb,left:(i%6)*320,top:Math.floor(i/6)*264});tiles.push({input:Buffer.from(`<svg width="320" height="24"><rect width="320" height="24" fill="#202020"/><text x="8" y="17" fill="white" font-size="16">${Math.round(f.timestamp)}s ${f.id}</text></svg>`),left:(i%6)*320,top:Math.floor(i/6)*264+240});}await sharp({create:{width:1920,height:Math.ceil(s.frames.length/6)*264,channels:3,background:'#202020'}}).composite(tiles).png().toFile('output/gym-contact.png');
const d=await new NodeIO().registerExtensions(ALL_EXTENSIONS).read(s.files.collision);const points=[],angles=new Map(),heights=new Map();
for(const m of d.getRoot().listMeshes())for(const p of m.listPrimitives()){const a=p.getAttribute('POSITION').getArray(),ind=p.getIndices().getArray();for(let n=0;n<ind.length;n+=3){const A=[...a.slice(ind[n]*3,ind[n]*3+3)],B=[...a.slice(ind[n+1]*3,ind[n+1]*3+3)],C=[...a.slice(ind[n+2]*3,ind[n+2]*3+3)];const u=B.map((x,i)=>x-A[i]),v=C.map((x,i)=>x-A[i]),norm=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],area=Math.hypot(...norm)/2,center=A.map((x,i)=>(x+B[i]+C[i])/3);const ny=norm[1]/(area*2);if(Math.abs(ny)<.1){const ang=(Math.atan2(norm[2],norm[0])*180/Math.PI+360)%90,k=Math.round(ang);angles.set(k,(angles.get(k)||0)+area);}if(Math.abs(ny)>.95){const k=Math.round(center[1]*20)/20;heights.set(k,(heights.get(k)||0)+area);}if(n%9===0)points.push(center);}}
console.log('Angles',JSON.stringify([...angles].sort((a,b)=>b[1]-a[1]).slice(0,12)));console.log('Height',JSON.stringify([...heights].sort((a,b)=>b[1]-a[1]).slice(0,18)));
console.log('Cameras',JSON.stringify(s.frames.map(f=>({id:f.id,t:Math.round(f.timestamp),p:f.camera.slice(0,3).map(r=>+r[3].toFixed(2)),forward:f.camera.slice(0,3).map(r=>+(-r[2]).toFixed(2))}))));
const scale=30,minx=-7,minz=-21,px=x=>(x-minx)*scale+35,py=z=>(z-minz)*scale+35;
let svg='<svg xmlns="http://www.w3.org/2000/svg" width="1050" height="1320"><rect width="100%" height="100%" fill="#182129"/>';
for(let x=-6;x<26;x++)svg+=`<line x1="${px(x)}" y1="25" x2="${px(x)}" y2="1290" stroke="#303a42"/><text x="${px(x)}" y="18" fill="white" font-size="9">${x}</text>`;
for(let z=-20;z<21;z++)svg+=`<line x1="25" y1="${py(z)}" x2="1020" y2="${py(z)}" stroke="#303a42"/><text x="7" y="${py(z)}" fill="white" font-size="9">${z}</text>`;
for(const p of points){if(p[1]>1.2||p[1]<-1.8)continue;svg+=`<circle cx="${px(p[0])}" cy="${py(p[2])}" r=".65" fill="${p[1]<-1.12?'#5b6268':p[1]<-.4?'#deb671':'#c4d5e0'}"/>`;}
for(const f of s.frames){const p=f.camera.slice(0,3).map(r=>r[3]);svg+=`<circle cx="${px(p[0])}" cy="${py(p[2])}" r="3" fill="#5cd5ff"/><text x="${px(p[0])+4}" y="${py(p[2])-3}" fill="#61e0ff" font-size="12">${Math.round(f.timestamp)}s</text>`;}
svg+='</svg>';await sharp(Buffer.from(svg)).png().toFile('output/gym-layout.png');
