import Foundation

/// Presents diagnostics from older Korean-language scans without editing stored data.
public enum DiagnosticText {
    public static func english(_ message: String) -> String {
        for (old, english) in legacy where message.hasPrefix(old) {
            return english + self.english(String(message.dropFirst(old.count)))
        }
        return message
    }

    private static let legacy: [(String, String)] = [
        ("중단된 세션에서 읽을 수 있는 데이터를 복구했습니다. 영상과 최종 메쉬가 없을 수 있습니다.", "Recovered readable data from an interrupted scan. The video or final mesh may be missing."),
        ("ZIP을 만들 저장 공간이 부족합니다. 원본은 보존되어 있습니다.", "There is not enough space to create the ZIP. Your original scan is saved."),
        ("파일이 변경되었습니다. 결과를 다시 검증해 주세요.", "The scan files have changed. Validate them again before exporting."),
        ("기기가 뜨겁습니다. 잠시 후 촬영을 마쳐 주세요.", "Your iPhone is getting hot. Finish your scan soon."),
        ("메쉬가 비어 있거나 면 인덱스가 잘못되었습니다.", "The mesh is empty or contains invalid face indices."),
        ("LiDAR를 지원하는 iPhone이 필요합니다.", "A LiDAR-enabled iPhone is required."),
        ("인덱스가 없는 바이너리 데이터가 있습니다.", "Binary data is missing an index entry."),
        ("메쉬 좌표 또는 인덱스가 잘못되었습니다.", "Invalid mesh coordinates or indices."),
        ("영상 샘플 수와 프레임 기록이 다릅니다.", "The video sample count does not match the frame records."),
        ("사용할 수 있는 카메라 포맷이 없습니다.", "No supported camera format is available."),
        ("누락 깊이에 바이너리 참조가 있습니다.", "A missing depth sample contains a binary reference."),
        ("일부 공간 데이터가 저장되지 않았습니다", "Some depth data could not be saved"),
        ("저장이 끝난 뒤 내보낼 수 있습니다.", "Wait until saving finishes before exporting."),
        ("파일 크기 또는 SHA-256 불일치", "File size or SHA-256 mismatch"),
        ("영상 회전 정보가 설정과 다릅니다.", "Video orientation does not match the recording settings."),
        ("추적이 불안정했던 구간이 있습니다.", "Tracking was unstable during part of the scan."),
        ("메타데이터 대기열이 가득 찼습니다.", "The metadata queue is full."),
        ("영상 인코더를 구성할 수 없습니다.", "Could not configure the video encoder."),
        ("저장되지 않은 프레임의 PTS: ", "PTS for an unwritten frame: "),
        ("일부 수집 샘플이 누락되었습니다.", "Some video or depth samples were missed."),
        ("저장된 깊이 데이터가 없습니다.", "No depth data was saved."),
        ("영상 해상도가 설정과 다릅니다.", "Video dimensions do not match the recording settings."),
        ("영상이 끝까지 읽히지 않습니다.", "The video could not be read to the end."),
        ("수집이 조기에 종료되었습니다: ", "Scan ended early: "),
        ("수집 이벤트 기록이 없습니다.", "No capture events were saved."),
        ("지원하지 않는 메쉬 버퍼 포맷", "Unsupported mesh buffer format"),
        ("완료되지 않은 마지막 행: ", "Incomplete final record: "),
        ("ZIP 파일 목록 검증 실패", "ZIP file list verification failed"),
        ("ZIP CRC 검증 실패: ", "ZIP CRC verification failed: "),
        ("ZIP 체크섬 검증 실패: ", "ZIP checksum verification failed: "),
        ("프레임 카메라 정보 오류: ", "Invalid camera metadata for frame: "),
        ("깊이 바이너리 범위 오류: ", "Invalid depth binary range for frame: "),
        ("깊이 내부 파라미터 오류: ", "Depth intrinsics mismatch for frame: "),
        ("영상 샘플 PTS 불일치: ", "Video sample PTS mismatch: "),
        ("비정상적으로 긴 데이터 행", "Data record exceeds the size limit"),
        ("깊이 프레임 연결 오류: ", "Depth frame association mismatch: "),
        ("주변을 천천히 비춰 주세요", "Move slowly to scan your surroundings"),
        ("발열로 수집을 종료합니다.", "Stopping the scan because your iPhone is overheating."),
        ("중복 frame_id: ", "Duplicate frame ID: "),
        ("영상 시간 대응 오류: ", "Video timestamp mismatch for frame: "),
        ("프레임 기록이 없습니다.", "No frame records were saved."),
        ("바이너리 파일 생성 실패", "Could not create a binary data file"),
        ("잘못된 픽셀 버퍼 크기", "Invalid pixel buffer dimensions"),
        ("삼각형이 아닌 메쉬 면", "Mesh contains a non-triangular face"),
        ("영상 트랙이 없습니다.", "No video track was found."),
        ("메쉬 파일 생성 실패", "Could not create the mesh file"),
        ("메쉬 UTF-8 오류", "Invalid UTF-8 in mesh file"),
        ("메쉬 면 인덱스 오류", "Invalid mesh face index"),
        ("저장되지 않은 프레임", "unwritten frame"),
        ("영상 저장 시작 실패", "Could not start recording video"),
        ("지원하는 iPhone", "Supported iPhone"),
        ("파일 생성 실패: ", "Could not create file: "),
        ("깊이 센서 준비 중", "Starting depth sensor"),
        ("잘못된 세션 ID", "Invalid session ID"),
        ("메쉬 꼭짓점 오류", "Invalid mesh vertex"),
        ("영상 마무리 실패", "Could not finalize the video"),
        ("천천히 이동하세요", "Move slowly"),
        ("프레임 검증: ", "Frame validation: "),
        ("이벤트 검증: ", "Event validation: "),
        ("영상 읽기 실패", "Could not read the video"),
        ("체크섬 검증: ", "Checksum verification: "),
        ("첫 수집 프레임", "First captured frame"),
        ("깊이 검증: ", "Depth validation: "),
        ("메쉬 검증: ", "Mesh validation: "),
        ("영상 검증: ", "Video validation: "),
        ("바이너리 범위", "depth binary range"),
        ("센서 준비 중", "Starting sensors"),
        ("깊이 수집 중", "Depth active"),
        ("저장 공간", "Storage"),
        ("일부 저장", "Partial"),
        ("저장 실패", "Failed"),
        ("수집 준비", "Preparing to scan"),
        ("추적 정상", "Tracking stable"),
        (" 프레임", " frames"),
        ("수집 중", "Scanning"),
        ("저장 중", "Saving"),
    ]
}
