import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import express from 'express';
import {z} from 'zod';
import {read,write} from './store';
const CHUNK=4*1024*1024,MAX_FILE=1536*1024*1024;
const names={mesh:'scene.glb',video:'video.mp4',frames:'frames.jsonl'} as const;
const kind=z.enum(['mesh','video','frames']);
const file=z.object({name:z.string().min(1).max(255),size:z.number().int().positive().max(MAX_FILE)});
const manifest=z.object({title:z.string().trim().min(1).max(100),files:z.object({mesh:file,video:file,frames:file.optional()})});
export function importDirectory(id:string){if(!/^import-[\w-]+$/.test(id))throw new Error('잘못된 가져오기 ID');return path.resolve('data/imports',id);}
export function launchImport(id:string){const dir=importDirectory(id),jobFile=path.join(dir,'job.json'),prior=read<any>(jobFile,{}),job={...prior,id,status:'queued',phase:'원본 준비 대기'};write(jobFile,job);const log=fs.openSync(path.join(dir,'prepare.log'),'a');const child=spawn(process.execPath,['--import','tsx','scripts/import-upload.ts',id],{cwd:process.cwd(),stdio:['ignore',log,log]});fs.closeSync(log);child.on('error',e=>write(jobFile,{...job,status:'failed',error:e.message}));child.on('exit',code=>{const latest=read<any>(jobFile,job);if(code!==0&&latest.status!=='failed')write(jobFile,{...latest,status:'failed',error:'입력 준비 프로세스가 중단되었습니다.'});});return job;}
export const uploads=express.Router();
uploads.post('/',(req,res)=>{const input=manifest.parse(req.body);if(!/\.glb$/i.test(input.files.mesh.name)||! /\.(mp4|mov|m4v)$/i.test(input.files.video.name)){res.status(400).json({error:'GLB와 MP4/MOV 원본 영상을 선택해 주세요.'});return;}const id=`import-${crypto.randomUUID()}`,dir=importDirectory(id);fs.mkdirSync(dir,{recursive:true});write(path.join(dir,'upload.json'),input);write(path.join(dir,'job.json'),{id,title:input.title,status:'uploading',phase:'원본 업로드 중',createdAt:new Date().toISOString()});res.status(201).json({id,chunkSize:CHUNK});});
uploads.put('/:id/:kind',express.raw({type:'application/octet-stream',limit:CHUNK}),(req,res)=>{const dir=importDirectory(String(req.params.id)),key=kind.parse(req.params.kind),input=read<z.infer<typeof manifest>|null>(path.join(dir,'upload.json'),null),job=read<any>(path.join(dir,'job.json'),null);if(!input||!job){res.status(404).json({error:'업로드를 찾을 수 없습니다.'});return;}if(job.status!=='uploading'){res.status(409).json({error:'이미 전처리가 시작된 업로드입니다.'});return;}const planned=input.files[key];if(!planned){res.status(400).json({error:'등록되지 않은 파일입니다.'});return;}const offset=z.coerce.number().int().nonnegative().parse(req.query.offset),dest=path.join(dir,names[key]),received=fs.existsSync(dest)?fs.statSync(dest).size:0;const bytes=req.body;if(!Buffer.isBuffer(bytes)||!bytes.length){res.status(400).json({error:'빈 전송 조각입니다.'});return;}if(offset!==received){res.status(409).json({error:'업로드 위치가 다릅니다. 다시 가져오기를 시작해 주세요.',received});return;}if(received+bytes.length>planned.size){res.status(413).json({error:'파일 크기를 초과했습니다.'});return;}fs.appendFileSync(dest,bytes);res.json({received:received+bytes.length,size:planned.size});});
uploads.post('/:id/complete',(req,res)=>{const id=String(req.params.id),dir=importDirectory(id),input=read<z.infer<typeof manifest>|null>(path.join(dir,'upload.json'),null),job=read<any>(path.join(dir,'job.json'),null);if(!input||!job){res.status(404).json({error:'업로드를 찾을 수 없습니다.'});return;}if(job.status!=='uploading'){res.status(202).json(job);return;}for(const key of Object.keys(input.files) as (keyof typeof names)[]){const f=path.join(dir,names[key]);if(!fs.existsSync(f)||fs.statSync(f).size!==input.files[key]!.size){res.status(400).json({error:'파일 업로드가 완료되지 않았습니다.'});return;}}res.status(202).json(launchImport(id));});
